# Generated by Django 3.2.4 on 2021-07-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='int',
            field=models.IntegerField(default=1),
        ),
    ]
